### PR TITLE
Update stable-req.txt

### PR DESCRIPTION
**Pull request by RAUFING**
New module translate

### CODE REVIEW

**Review by alexpvpmindustry — COMMENTED** [review]
its translate==3.6.1, not translate=3.6.1

**Comment by leblancogato** [comment]
lemme fix it then

**Comment by leblancogato** [comment]
how do I commit on pull req

**Review by leblancogato — CHANGES_REQUESTED** [review]
oi blyad change the = to == in the module thing

**Review by leblancogato — APPROVED** [review]
I fixed it

**Pull request merged**
