### PR TITLE
add eval command

### PR DESCRIPTION
**Pull request by WilloIzCitron**
eval command is evaluation code of python or stuff like
w?eval 1+1
ouput its 2
this command is for developer

### CODE REVIEW

**Comment by alexpvpmindustry** [comment]
ill keep this in consideration... seems to dangerous to allow arbitrary python code evaluation (even for me).
i cant see the use case such that the benefit is greater than the potential security vulnerability.
(since this could allow printing of config secrets/tokens and alter the code files itself.)
if i need to run python, i can use the ide.

Do you mind explaining what are the use case for this?

**Comment by WilloIzCitron** [comment]
oh ok

**Comment by WilloIzCitron** [comment]
but a token and mongodb link its in .env and load with os.environ.get

**Comment by WilloIzCitron** [comment]
i change my mind its used with json

**Comment by WilloIzCitron** [comment]
updating :wink:

**Pull request closed without merging**
